version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.4.2
      - image: cimg/postgres:16.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: satisfactory_dummy_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      PGHOST: 127.0.0.1
      PGUSER: postgres
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run the default task
          command: bundle exec rake
